### ISSUE TITLE
Quick suggestion

### ISSUE THREAD

**Issue by master-atul** [irustm/angular-nodegui#4]
Hi @irustm 

First of all amazing work.

Not sure if you know this already, NodeGui supports `setProperty` (https://doc.qt.io/qt-5/qobject.html#setProperty)  method on all widgets and components that inherit from QObject. 

The interesting point of this method is that you can set any property on all the widgets (even the ones that havent been implemented in NodeGui. 

For example:

The following properties can be set on qpushbutton using this method. 
https://doc.qt.io/qt-5/qpushbutton.html#properties 

Just a quick suggestion and you may close this issue straightaway.

**Comment by irustm** [comment]
Wow! Thank you! 
I now definitely have to remake =)
